### ISSUE TITLE
apidocs

### ISSUE THREAD

**Issue by lillian-lemmer** [lillian-lemmer/hypatia#35]
need to write apidocs

**Comment by SanketDG** [comment]
Do you mean documentation generated from docstrings?

**Comment by lillian-lemmer** [comment]
Pretty much. Do you know of anything that outputs to asciidoc? I guess I could use pandoc. I really odn't wnat to get into a large, complicated apigen tool like sphinx or whatever.

**Comment by SanketDG** [comment]
Does pandoc support documentation generation from docstrings? Then that could be used, I guess.
I found another very simple and easy-to-use library, [mkdocs](https://github.com/mkdocs/mkdocs]

**Comment by lillian-lemmer** [comment]
Pandoc is mostly for converstion. I've used some auto api tools in the past, but their name escapes me. I'd like something that natively supports asciidoc. I used to use a one-command apigen, I can't remember the name.

**Comment by lillian-lemmer** [comment]
I mean, I want something that globs docstrings and generates api docs from that, output being asciidoc

**Comment by SanketDG** [comment]
Maybe this will refresh your memory, https://wiki.python.org/moin/DocumentationTools

**Comment by lillian-lemmer** [comment]
Actually come to think of it, since I use Google style docstrings I better use Sphinx, anyway. I wonder if I should create a new site or just use my wiki... hrm...

**Comment by ejmr** [comment]
> Does pandoc support documentation generation from docstrings?

No, it does not.  Although that would be an interesting plugin to write for it.  Thanks for the idea.

**Comment by lillian-lemmer** [comment]
That would be the best thing ever, @ejmr.

**Comment by ejmr** [comment]
An idea I had this morning is to use something like [`Docstring_page`](https://github.com/DataBranner/Docstring_Page) to extract docstrings from all the `*.py` files.  That program creates output in Markdown format but Pandoc can convert that to damn near anything.  Within the `main()` function of that program I had to set `tests_only` to `False` by default to get any meaningful output, and even then I wasn't crazy about the formatting it produced, but it could be a useful tool with some tweaks.

That said, I would still rather extend Pandoc since I use that tool daily.

**Comment by lillian-lemmer** [comment]
Yeah, same, I love pandoc. :)

**Comment by lillian-lemmer** [comment]
I'm using sphinx. See `sphinx-source`, `sphinx-source/readme.asciidoc`, and `make-sphinx.sh`. Also: http://lillian-lemmer.github.io/hypatia/api.
