### ISSUE TITLE
pip version presumptions; poor install script in-code documentation

### ISSUE THREAD

**Issue by jwl** [lillian-lemmer/hypatia#48]
If a user follows the installation instructions for Ubuntu to the letter, upon running `./test.sh` they will encounter a pip error stating that `"--no-cache-dir"` option doesn't exist. This is due to the fact that the install instructions have the user install pip from Ubuntu's repository. Ubuntu's repository uses pip version 1.5.6. The `--no-cache-dir` option was implemented starting in version 6.0 (see [pip reference guide](https://pip.pypa.io/en/latest/reference/pip_install.html#caching)). 

Either test.sh needs to be edited to no longer use the `--no-cache-dir` option or the [Installation-Ubuntu](https://github.com/lillian-lemmer/hypatia/wiki/Installation-Ubuntu) instructions and scripts need to be amended to use the [get-pip.py installation method](https://pip.pypa.io/en/latest/installing.html), which will install the latest version of pip (7.1.0).

**Comment by ejmr** [comment]
As an Ubuntu user I'd vote in favor of the method for updating pip.  I didn't run into this error myself since I keep pip (and a separate pip3) as up to date as possible.

**Comment by lillian-lemmer** [comment]
@ejmr do you think it'd be good/bad to auto-update for people in the script? I generally don't like touching people's delicate software ecosystems.

**Comment by ejmr** [comment]
> do you think it'd be good/bad to auto-update for people in the script?

Sorry, what specifically are you talking about auto-updating?  `pip`?

**Comment by lillian-lemmer** [comment]
Yes, pip. But then I came to the conclusion, "Well, why then would you stop at pip?" I think that can be kinda intrusive? Should we just note which version of pip you'll need?

**Comment by ejmr** [comment]
>  I think that can be kinda intrusive? Should we just note which version of pip you'll need?

Yeah, I think we should note that (regardless really), but I also agree with you that we shouldn't be intrusive.  As it is the installation scripts require `sudo` so that should give the user reason to stop and pause; but it would be better if we modified the scripts to first explain what they're about to install so that the user knows *why* we're asking for `sudo` permissions.  This is of course all assuming we want to keep such installation scripts.  If we make it very clear in the documentation what users/developers need to install then we can leave it to their own devices to install and setup those tools in the most appropriate way for their system.  I think that approach would be fine for any pre-requisites for *developers* who want to work on Hypatia because we can fairly expect them to be able to setup their own development environment.  For *users* who need to install things simply to run Hypatia and games built with it, I think we should provide them with install scripts, but they should be very clear in communicating what they install, ideally even having information about the "normal channels" for installation for the more common operating systems, recommending those over our own installation scripts.

**Comment by lillian-lemmer** [comment]
Sounds good to me. I'll try to get around to that.

**Comment by lillian-lemmer** [comment]
Resolved in https://github.com/lillian-lemmer/hypatia/commit/4bb33eeaaf1026976e25e8cb5b5eaa8556cac0bb
