### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by pywkm** [lillian-lemmer/hypatia#6]
Hi,
I'm just wondering why you're not making this project also Python 3 compatible. I know that you've just started, so it would be much more easier _now_ to think about that, than two years from now, when this package will be very successful and there will be many more complains "why this isn't working in Py3!?". ;-)
Regards,
Wiktor

(I managed to make it work under Py3 and Py2, but I don't know if all hacks are Pythonic enough, so I would rather not commit anything now (even if you are OK with Py3 compatibility). I'm novice, learning Pygame myself, and for now I want to just understand how this engine works, and not to break anything) :-)

**Comment by lillian-lemmer** [comment]
This is a great point, I think I did this out of ignorance, thinking that pygame was only available for Python 2, but clearly it's out now for Python 3.

There's always the testing branch, dear! If we talk a bit more on Skype, email, or IRC, we can go over the various aspects of the engine. This would be incredibly valuable to me, because it'll help me identify what needs to be put into the documentation, and any questions you may have will probably be useful for the general public, too.

Thank you for your quality contribution, I believe you truly saved me a lot of hassle reminding me of this error. I will be resolving this issue in the next commit to testing.

**Comment by lillian-lemmer** [comment]
Python 3 compatibility is almost finished. Working on a weird quirk where, what I'm guessing is a difference between Pillow and PIL, the walkabout sprite has an extra pixel of overhead padding/rect space. Not sure why this is exactly. Will push once determined.

**Comment by lillian-lemmer** [comment]
Was an issue with floor division. Resolved; Python 3 support added. Tested functional in Python 2.7 and 3.4 in Linuxmint.

**Comment by lillian-lemmer** [comment]
Was an issue with floor division. Resolved; Python 3 support added. Tested functional in Python 2.7 and 3.4 in Linuxmint.
